### PR TITLE
optimize yyjson

### PR DESCRIPTION
**Pull request by ibireme**
I tried making yyjson benchmark faster by:
- Reusing memory with an allocator (like simdjson parser does).
- Skipping unnecessary string length checks.

Tested on M1 Pro, AppleClang 15. 
Before:
| Library                                                      | Roundtrip Time (s) | Write (MB/s) | Read (MB/s) |
| ------------------------------------------------------------ | ------------------ | ------------ | ----------- |
| [**Glaze**](https://github.com/stephenberry/glaze) | **1.24** | **1052** | **1057** |
| [**simdjson (on demand)**](https://github.com/simdjson/simdjson) | **N/A** | **N/A** | **1195** |
| [**yyjson**](https://github.com/ibireme/yyjson) | **1.51** | **779** | **992** |
| [**daw_json_link**](https://github.com/beached/daw_json_link) | **2.89** | **368** | **565** |
| [**RapidJSON**](https://github.com/Tencent/rapidjson) | **3.66** | **291** | **445** |
| [**Boost.JSON (direct)**](https://boost.org/libs/json) | **4.69** | **202** | **448** |
| [**json_struct**](https://github.com/jorgen/json_struct) | **5.42** | **182** | **344** |
| [**nlohmann**](https://github.com/nlohmann/json) | **15.29** | **86** | **83** |

This PR:

| Library                                                      | Roundtrip Time (s) | Write (MB/s) | Read (MB/s) |
| ------------------------------------------------------------ | ------------------ | ------------ | ----------- |
| [**Glaze**](https://github.com/stephenberry/glaze) | **1.24** | **1061** | **1066** |
| [**simdjson (on demand)**](https://github.com/simdjson/simdjson) | **N/A** | **N/A** | **1190** |
| [**yyjson**](https://github.com/ibireme/yyjson) | **1.23** | **1006** | **1112** |
| [**daw_json_link**](https://github.com/beached/daw_json_link) | **2.91** | **368** | **563** |
| [**RapidJSON**](https://github.com/Tencent/rapidjson) | **3.70** | **291** | **442** |
| [**Boost.JSON (direct)**](https://boost.org/libs/json) | **4.70** | **201** | **448** |
| [**json_struct**](https://github.com/jorgen/json_struct) | **5.42** | **181** | **343** |
| [**nlohmann**](https://github.com/nlohmann/json) | **15.32** | **86** | **82** |

I noticed that the memory allocator has some effect on speed. 
So I also ran a test without changing the code, just by switching the allocator:
```bash
brew install mimalloc
env DYLD_INSERT_LIBRARIES=/opt/homebrew/lib/libmimalloc.dylib ./json_performance
```
| Library                                                      | Roundtrip Time (s) | Write (MB/s) | Read (MB/s) |
| ------------------------------------------------------------ | ------------------ | ------------ | ----------- |
| [**Glaze**](https://github.com/stephenberry/glaze) | **1.23** | **1060** | **1069** |
| [**simdjson (on demand)**](https://github.com/simdjson/simdjson) | **N/A** | **N/A** | **1197** |
| [**yyjson**](https://github.com/ibireme/yyjson) | **1.31** | **904** | **1068** |
| [**daw_json_link**](https://github.com/beached/daw_json_link) | **2.66** | **367** | **714** |
| [**RapidJSON**](https://github.com/Tencent/rapidjson) | **3.49** | **307** | **457** |
| [**Boost.JSON (direct)**](https://boost.org/libs/json) | **4.26** | **233** | **450** |
| [**json_struct**](https://github.com/jorgen/json_struct) | **5.35** | **183** | **349** |
| [**nlohmann**](https://github.com/nlohmann/json) | **12.57** | **114** | **93** |

### CODE REVIEW

**Comment by stephenberry** [comment]
Neat! Thanks for these updates! I'll merge this when I get a bit of time to look it over.

**Comment by stephenberry** [comment]
@ibireme, what is going on with the `const_cast`? Can we just take in a non-const string?
`auto const doc = yyjson_read_opts(const_cast<char*>(json.data()), json.size(), 0, alc, nullptr);`

If you could remove the const_cast that would be great. I just want others to be able to use this codebase as a reference for how to optimally use libraries, so I wouldn't want someone else copying this. Thanks!

**Comment by ibireme** [comment]
>  `auto const doc = yyjson_read_opts(const_cast<char*>(json.data()), json.size(), 0, alc, nullptr);`
> If you could remove the const_cast that would be great. I just want others to be able to use this codebase as a reference for how to optimally use libraries, so I wouldn't want someone else copying this. Thanks!

It can be a bit confusing, and this question has come up before: https://github.com/ibireme/yyjson/issues/93. 

This function may modify the input string when using the `YYJSON_READ_INSITU` flag,  so it has to be declared as `char*`. If the caller tries to pass in a `const char*`, a type conversion is necessary to explicitly remove the `const`.

**Comment by stephenberry** [comment]
Thanks for the explanation. Since this is a known requirement of the API I'll go ahead and merge it in.

**Pull request merged**
